spring.application.name=DataApp
spring.config.import=optional:secrets.properties
spring.data.mongodb.uri=mongodb://localhost:27017/Movie-App
spring.data.mongodb.database=Movie-App
server.port = 8081
spring.main.lazy-initialization=false


tmdb.apiKey = <tmdb_api_key>
rzpay.keyId = <razorpay_api_key>
rzpay.secret = <razorpay_key_secret>